posts:
  per_page: 3
messages:
  max_length: 1000
users:
  email_max_leng: 255
  email_min_leng: 8
  name_max_leng: 63
  name_min_leng: 4
  avatar_size:
    header: 50
    comments: 100
    liked: 25
comments:
  content_max_leng: 1000
feedbacks:
  content_max_leng: 1000
  title_max_leng: 255
posts:
  content_max_leng: 50000
  title_max_leng: 255
